name: e_voting_app
description: An E-Voting prototype appilication for Lost Votes challange.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #thisd party dependency
  cupertino_icons: ^1.0.0
  toast: ^0.1.5
  local_auth: ^0.6.2+3
  provider: ^4.3.2
  shared_preferences: ^0.5.8
  synchronized: ^2.2.0+2
  scroll_to_index: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
